CREATE TABLE "cashapp_models_currency" ("id" serial NOT NULL PRIMARY KEY, "guid" varchar(40) NOT NULL UNIQUE, "is_exist" boolean NOT NULL, "code" varchar(3) NOT NULL UNIQUE, "hex" varchar(10) NOT NULL, "dec" varchar(20) NOT NULL, "label" varchar(30) NULL);
CREATE TABLE "cashapp_models_language" ("id" serial NOT NULL PRIMARY KEY, "code" varchar(2) NOT NULL UNIQUE);
CREATE TABLE "cashapp_models_paymentobject" ("id" serial NOT NULL PRIMARY KEY, "guid" varchar(40) NOT NULL UNIQUE, "is_exist" boolean NOT NULL, "name" varchar(30) NULL, "is_locked" boolean NOT NULL, "allow_negative" boolean NOT NULL, "currency_id" varchar(3) NOT NULL);
CREATE TABLE "cashapp_models_pers" ("id" serial NOT NULL PRIMARY KEY, "language_id" varchar(2) NOT NULL, "user_id" integer NOT NULL UNIQUE);
CREATE TABLE "cashapp_models_poregister" ("id" serial NOT NULL PRIMARY KEY, "guid" varchar(40) NOT NULL UNIQUE, "is_exist" boolean NOT NULL, "date" timestamp with time zone NOT NULL, "balance" numeric(17, 2) NOT NULL, "payment_object_id" varchar(40) NOT NULL);
CREATE TABLE "cashapp_models_potype" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(10) NOT NULL UNIQUE);
CREATE TABLE "cashapp_models_widget" ("id" serial NOT NULL PRIMARY KEY, "guid" varchar(40) NOT NULL UNIQUE, "is_exist" boolean NOT NULL, "object_type" varchar(40) NOT NULL, "object_guid" varchar(40) NOT NULL, "order_number" smallint NULL CHECK ("order_number" >= 0), "pers_id" integer NOT NULL);
ALTER TABLE "cashapp_models_paymentobject" ADD COLUMN "type_id" varchar(10) NOT NULL;
ALTER TABLE "cashapp_models_paymentobject" ALTER COLUMN "type_id" DROP DEFAULT;
ALTER TABLE "cashapp_models_paymentobject" ADD COLUMN "user_id" integer NOT NULL;
ALTER TABLE "cashapp_models_paymentobject" ALTER COLUMN "user_id" DROP DEFAULT;
CREATE INDEX "cashapp_models_currency_guid_5856e3e8921117b6_like" ON "cashapp_models_currency" ("guid" varchar_pattern_ops);
CREATE INDEX "cashapp_models_currency_code_7445a88a1b721ce_like" ON "cashapp_models_currency" ("code" varchar_pattern_ops);
CREATE INDEX "cashapp_models_language_code_50bdf92aec58ebd1_like" ON "cashapp_models_language" ("code" varchar_pattern_ops);
ALTER TABLE "cashapp_models_paymentobject" ADD CONSTRAINT "ca_currency_id_649169bf88526b4e_fk_cashapp_models_currency_code" FOREIGN KEY ("currency_id") REFERENCES "cashapp_models_currency" ("code") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_paymentobject_2c7d5721" ON "cashapp_models_paymentobject" ("currency_id");
CREATE INDEX "cashapp_models_paymentobject_guid_194bf422fea1d543_like" ON "cashapp_models_paymentobject" ("guid" varchar_pattern_ops);
CREATE INDEX "cashapp_models_paymentobject_currency_id_649169bf88526b4e_like" ON "cashapp_models_paymentobject" ("currency_id" varchar_pattern_ops);
ALTER TABLE "cashapp_models_pers" ADD CONSTRAINT "ca_language_id_388ce63c5425d619_fk_cashapp_models_language_code" FOREIGN KEY ("language_id") REFERENCES "cashapp_models_language" ("code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "cashapp_models_pers" ADD CONSTRAINT "cashapp_models_pers_user_id_2064028908e2a51e_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_pers_468679bd" ON "cashapp_models_pers" ("language_id");
CREATE INDEX "cashapp_models_pers_language_id_388ce63c5425d619_like" ON "cashapp_models_pers" ("language_id" varchar_pattern_ops);
ALTER TABLE "cashapp_models_poregister" ADD CONSTRAINT "e6b5a341422d295566572807afe542ca" FOREIGN KEY ("payment_object_id") REFERENCES "cashapp_models_paymentobject" ("guid") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_poregister_7c1e1a4b" ON "cashapp_models_poregister" ("payment_object_id");
CREATE INDEX "cashapp_models_poregister_guid_34ead8d11d5b84ed_like" ON "cashapp_models_poregister" ("guid" varchar_pattern_ops);
CREATE INDEX "cashapp_models_poregist_payment_object_id_29059ad5a419b5fb_like" ON "cashapp_models_poregister" ("payment_object_id" varchar_pattern_ops);
CREATE INDEX "cashapp_models_potype_name_735741cecc98a678_like" ON "cashapp_models_potype" ("name" varchar_pattern_ops);
ALTER TABLE "cashapp_models_widget" ADD CONSTRAINT "cashapp_mode_pers_id_5edb80542f2ace79_fk_cashapp_models_pers_id" FOREIGN KEY ("pers_id") REFERENCES "cashapp_models_pers" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_widget_9247b31c" ON "cashapp_models_widget" ("pers_id");
CREATE INDEX "cashapp_models_widget_guid_63245d84202d422f_like" ON "cashapp_models_widget" ("guid" varchar_pattern_ops);
CREATE INDEX "cashapp_models_paymentobject_94757cae" ON "cashapp_models_paymentobject" ("type_id");
ALTER TABLE "cashapp_models_paymentobject" ADD CONSTRAINT "cashapp_m_type_id_1a11eec542e1d9f_fk_cashapp_models_potype_name" FOREIGN KEY ("type_id") REFERENCES "cashapp_models_potype" ("name") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_paymentobject_e8701ad4" ON "cashapp_models_paymentobject" ("user_id");
ALTER TABLE "cashapp_models_paymentobject" ADD CONSTRAINT "cashapp_models_payment_user_id_574186d7bf2876d6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
