CREATE TABLE "cashapp_models_currency" ("id" serial NOT NULL PRIMARY KEY, "code" varchar(3) NOT NULL UNIQUE, "hex" varchar(10) NOT NULL, "dec" varchar(20) NOT NULL, "label" varchar(30) NULL);
CREATE TABLE "cashapp_models_paymentobject" ("id" serial NOT NULL PRIMARY KEY, "guid" varchar(40) NOT NULL UNIQUE, "is_exist" boolean NOT NULL, "name" varchar(30) NULL, "is_locked" boolean NOT NULL, "allow_negative" boolean NOT NULL, "currency_id" varchar(3) NOT NULL);
CREATE TABLE "cashapp_models_poregister" ("id" serial NOT NULL PRIMARY KEY, "guid" varchar(40) NOT NULL UNIQUE, "is_exist" boolean NOT NULL, "date" timestamp with time zone NOT NULL, "balance" numeric(17, 2) NOT NULL, "finance_id" varchar(40) NOT NULL);
CREATE TABLE "cashapp_models_potype" ("id" serial NOT NULL PRIMARY KEY, "name" varchar(10) NOT NULL UNIQUE);
ALTER TABLE "cashapp_models_paymentobject" ADD COLUMN "type_id" varchar(10) NOT NULL;
ALTER TABLE "cashapp_models_paymentobject" ALTER COLUMN "type_id" DROP DEFAULT;
ALTER TABLE "cashapp_models_paymentobject" ADD COLUMN "user_id" integer NOT NULL;
ALTER TABLE "cashapp_models_paymentobject" ALTER COLUMN "user_id" DROP DEFAULT;
CREATE INDEX "cashapp_models_currency_code_7445a88a1b721ce_like" ON "cashapp_models_currency" ("code" varchar_pattern_ops);
ALTER TABLE "cashapp_models_paymentobject" ADD CONSTRAINT "ca_currency_id_649169bf88526b4e_fk_cashapp_models_currency_code" FOREIGN KEY ("currency_id") REFERENCES "cashapp_models_currency" ("code") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_paymentobject_2c7d5721" ON "cashapp_models_paymentobject" ("currency_id");
CREATE INDEX "cashapp_models_paymentobject_guid_194bf422fea1d543_like" ON "cashapp_models_paymentobject" ("guid" varchar_pattern_ops);
CREATE INDEX "cashapp_models_paymentobject_currency_id_649169bf88526b4e_like" ON "cashapp_models_paymentobject" ("currency_id" varchar_pattern_ops);
ALTER TABLE "cashapp_models_poregister" ADD CONSTRAINT "b447d93c7c15f2afc1d8cfce5262f840" FOREIGN KEY ("finance_id") REFERENCES "cashapp_models_paymentobject" ("guid") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_poregister_65ed131b" ON "cashapp_models_poregister" ("finance_id");
CREATE INDEX "cashapp_models_poregister_guid_34ead8d11d5b84ed_like" ON "cashapp_models_poregister" ("guid" varchar_pattern_ops);
CREATE INDEX "cashapp_models_poregister_finance_id_61573b910beee740_like" ON "cashapp_models_poregister" ("finance_id" varchar_pattern_ops);
CREATE INDEX "cashapp_models_potype_name_735741cecc98a678_like" ON "cashapp_models_potype" ("name" varchar_pattern_ops);
CREATE INDEX "cashapp_models_paymentobject_94757cae" ON "cashapp_models_paymentobject" ("type_id");
ALTER TABLE "cashapp_models_paymentobject" ADD CONSTRAINT "cashapp_m_type_id_1a11eec542e1d9f_fk_cashapp_models_potype_name" FOREIGN KEY ("type_id") REFERENCES "cashapp_models_potype" ("name") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "cashapp_models_paymentobject_e8701ad4" ON "cashapp_models_paymentobject" ("user_id");
ALTER TABLE "cashapp_models_paymentobject" ADD CONSTRAINT "cashapp_models_payment_user_id_574186d7bf2876d6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;